# Checkov Configuration for k8s-OSS Project
# 이 파일은 k8s-OSS 프로젝트의 Kubernetes, Helm, Dockerfile 보안 스캔 설정을 정의합니다.

# 기본 동작 설정
quiet: true                           # 간결한 출력 (CI/CD 환경에 적합)
framework:                            # 스캔할 프레임워크 지정
  - kubernetes                        # Kubernetes YAML 매니페스트
  - helm                             # Helm 차트 템플릿
  - dockerfile                       # Dockerfile 및 컨테이너 설정

# 고급 스캔 옵션
download-external-modules: true       # 외부 모듈/템플릿 다운로드 및 평가 (Helm 차트 등)
evaluate-variables: true              # 변수 값 평가로 더 정확한 분석

# 출력 설정
output: cli                          # 기본 출력 형식 (워크플로우에서 override됨)

# 실패 기준 (점진적 도입을 위한 설정)
# 처음 도입 시에는 soft-fail-on을 사용하여 단계적으로 강화 가능
# soft-fail-on: medium               # MEDIUM 이하는 경고, HIGH 이상만 실패 처리

# 팀 합의된 예외 경로
skip-path:
#  - "tests/"                         # 테스트 디렉터리
#  - "experimental/"                  # 실험적 코드 디렉터리
#  - "examples/"                      # 예제 코드 디렉터리
#  - "docs/"                          # 문서 디렉터리
  - ".git/"                          # Git 메타데이터
#  - "node_modules/"                  # Node.js 의존성

# 특정 체크 전역 예외 (최소화 권장)
# 개별 파일에서는 인라인 주석으로 예외 처리 권장: # checkov:skip=CKV_K8S_21:Reason
# skip-check:
#   - CKV_K8S_21                     # 예: 특정 보안 체크 제외

# 심각도별 필터링 (선택사항)
# check-severity: HIGH,CRITICAL      # HIGH, CRITICAL 이슈만 체크

# 커스텀 정책 디렉터리 (있는 경우)
# external-checks-dir: custom-policies/

# 보고서 설정
# compact: true                      # 간결한 보고서 형식
# quiet: false                       # 상세한 로그 출력 (디버깅 시 사용)

# 성능 최적화
# parallel: true                     # 병렬 처리 활성화 (대용량 프로젝트용)

# 추가 설정 예시 (필요시 주석 해제)
# repo-root-for-plan-enrichment: .   # Terraform plan 강화를 위한 루트 디렉터리
# download-external-modules: false   # 외부 모듈 다운로드 비활성화 (빠른 스캔용)
# evaluate-variables: false          # 변수 평가 비활성화 (빠른 스캔용)