## Keycloak Helm Values
## 이 파일은 Keycloak을 Kubernetes에 설치할 때 사용하는 Helm values입니다.

## keycloak admin 유저 ID/Passwd 설정
auth:
  adminUser: admin
  adminPassword: "your-admin-password"

## 서비스는 ClusterIP로만 노출 (LoadBalancer 타입 제거)
service:
  type: ClusterIP
  # service.annotations, aws-load-balancer 설정 모두 제거

## HTTP/HTTPS 포트 매핑 (ClusterIP에서는 포트만 지정)
ports:
  http: 80
  https: 443

## Ingress → AWS ALB
ingress:
  enabled: true
  ingressClassName: alb
  hostname: keycloak.bluesunnywings.com
  path: /
  pathType: Prefix
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:219967435143:certificate/5d011410-cf0a-4412-94fd-9482bed70ef8"
    alb.ingress.kubernetes.io/group.name: common-ingress
    external-dns.alpha.kubernetes.io/hostname: "keycloak.bluesunnywings.com"
    alb.ingress.kubernetes.io/target-type: ip
  tls: true

## TLS 설정 (ALB에서 HTTPS 종료하므로 내부는 HTTP 사용)
tls:
  enabled: false
  autoGenerated:
    enabled: false

## 내장 PostgreSQL 데이터베이스 설정
postgresql:
  enabled: true ## external DB 사용할 경우 false로 변경
  auth:
    postgresPassword: "postgres123"
    username: admin_keycloak
    password: "keycloak123"
    database: db_keycloak
    existingSecret: ""
  architecture: standalone
  tls:
    enabled: false
    autoGenerated:
      enabled: false

## external DB 사용할 경우 정보 입력
externalDatabase:
  host: ""
  port: 5432
  user: ""
  database: ""
  password: ""
  existingSecret: ""
  existingSecretPasswordKey: ""