apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench-comprehensive
  namespace: default
  labels:
    app: kube-bench
    type: comprehensive-audit
  annotations:
    description: "Comprehensive security benchmark for all node types"
spec:
  # ë³‘ë ¬ ì‹¤í–‰ìœ¼ë¡œ ì„±ëŠ¥ ìµœì í™”
  parallelism: 3
  completions: 3
  backoffLimit: 2
  activeDeadlineSeconds: 1800  # 30ë¶„ íƒ€ìž„ì•„ì›ƒ
  
  template:
    metadata:
      labels:
        app: kube-bench
    spec:
      restartPolicy: Never
      hostPID: true
      
      # ë…¸ë“œ íƒ€ìž…ë³„ ë¶„ì‚° ì‹¤í–‰
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: ["kube-bench"]
              topologyKey: kubernetes.io/hostname
      
      tolerations:
      - operator: Exists
      
      containers:
      - name: kube-bench
        image: aquasec/kube-bench:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "ðŸš€ Starting comprehensive kube-bench audit..."
          
          # ë…¸ë“œ íƒ€ìž… ê°ì§€
          if kubectl get nodes $NODE_NAME -o jsonpath='{.metadata.labels}' | grep -q "node-role.kubernetes.io/control-plane"; then
            echo "ðŸ“‹ Running master node checks..."
            kube-bench --targets master --json > /tmp/master-results.json
            kube-bench --targets master > /tmp/master-results.txt
          else
            echo "ðŸ“‹ Running worker node checks..."
            kube-bench --targets node --json > /tmp/node-results.json
            kube-bench --targets node > /tmp/node-results.txt
          fi
          
          # EKS íŠ¹í™” ê²€ì‚¬
          if kubectl get configmap -n kube-system aws-auth &>/dev/null; then
            echo "ðŸ“‹ Running EKS-specific checks..."
            kube-bench --benchmark eks-1.2.0 --json > /tmp/eks-results.json
            kube-bench --benchmark eks-1.2.0 > /tmp/eks-results.txt
          fi
          
          echo "âœ… Audit completed successfully"
          
          # ê²°ê³¼ ìš”ì•½ ì¶œë ¥
          echo "ðŸ“Š Results Summary:"
          for file in /tmp/*-results.txt; do
            if [ -f "$file" ]; then
              echo "--- $(basename $file) ---"
              grep -E "\[(PASS|FAIL|WARN)\]" "$file" | sort | uniq -c
            fi
          done
        
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        
        volumeMounts:
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
          readOnly: true
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
          readOnly: true
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        - name: usr-bin
          mountPath: /usr/local/mount-from-host/bin
          readOnly: true
        - name: etc-cni-netd
          mountPath: /etc/cni/net.d/
          readOnly: true
        - name: opt-cni-bin
          mountPath: /opt/cni/bin/
          readOnly: true
      
      volumes:
      - name: var-lib-etcd
        hostPath:
          path: "/var/lib/etcd"
      - name: var-lib-kubelet
        hostPath:
          path: "/var/lib/kubelet"
      - name: etc-kubernetes
        hostPath:
          path: "/etc/kubernetes"
      - name: usr-bin
        hostPath:
          path: "/usr/bin"
      - name: etc-cni-netd
        hostPath:
          path: "/etc/cni/net.d/"
      - name: opt-cni-bin
        hostPath:
          path: "/opt/cni/bin/"