apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: prometheus
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus:9090
      isDefault: true
      access: proxy
    - name: Loki
      type: loki
      url: http://loki:3100
      access: proxy
    - name: Tempo
      type: tempo
      url: http://tempo:3100
      access: proxy
      jsonData:
        tracesToLogs:
          datasourceUid: loki
          tags: ["job", "instance", "pod", "namespace"]
          mappedTags: [{"key": "service.name", "value": "service"}]
          mapTagNamesEnabled: false
          spanStartTimeShift: "1h"
          spanEndTimeShift: "1h"
          filterByTraceID: false
          filterBySpanID: false
        lokiSearch:
          datasourceUid: loki
        serviceMap:
          datasourceUid: prometheus