apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-keycloak
  namespace: argo-cd
spec:
  # 1분마다 AWS Secrets Manager에서 동기화
  refreshInterval: 1m
  
  # SecretStore 참조
  secretStoreRef:
    kind: SecretStore
    name: aws-secretsmanager-argo-cd
  
  # 대상 Kubernetes Secret 설정
  target:
    name: argocd-secret
    creationPolicy: Merge  # 기존 Secret에 병합
    deletionPolicy: Retain # ExternalSecret 삭제 시 Secret 유지
  
  # AWS Secrets Manager에서 가져올 데이터
  data:
  - secretKey: oidc.keycloak.clientSecret
    remoteRef:
      key: argocd/oidc/keycloak
      property: oidc.keycloak.clientSecret

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager-argo-cd
  namespace: argo-cd
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      # IAM Role을 사용하는 경우 (권장)
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
      # 또는 Access Key를 사용하는 경우
      # auth:
      #   secretRef:
      #     accessKeyIDSecretRef:
      #       name: aws-credentials
      #       key: access-key-id
      #     secretAccessKeySecretRef:
      #       name: aws-credentials
      #       key: secret-access-key