apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-app-jmx-monitor
  namespace: lgtm-stack
  labels:
    app: java-sample-app
    monitoring: lgtm-stack
    release: prometheus-agent
spec:
  selector:
    matchLabels:
      app: java-sample-app-svc
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: jmx-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true